"""Test-function bases used to realize the weak lifts of the paper.

The weak lifts U_L^u, X_K^x, Y_K^y, Z_L^{x,u} from
`paper_informativity/sections/preliminaries.tex` are operators on
test-function spaces D(I) = C_c^\\infty(I). In practice we replace D(I)
by a finite-dimensional span Phi = (phi_1, ..., phi_N) whose elements
are smooth enough for the pairings we actually compute.

Each basis below exposes three primitives over a time grid `ts`:
    - phi(ts)     -> (N_time, N_basis)
    - phi_d(ts, k) -> (N_time, N_basis)  pointwise k-th derivative

Whenever data live in the Sobolev space H^{K-1}(I) (the standard case
when trajectories are generated by an SDE with additive noise, since
x lies in H^1 a.s.), the pairing `<f, phi>` reduces to the integral
int_0^T f(t) phi(t) dt and higher weak derivatives <D^k f, phi> can
be moved onto the test function via integration by parts,
    <D^k f, phi> = (-1)^k <f, D^k phi>,
which is numerically far more stable than differentiating noisy f.
The modules `lifts.py` and `identification.py` use that identity.

Two concrete families are provided:
    - FourierSineBasis (L^2, actually H^infty ∩ H^1_0)
    - BumpBasis (C^infty with compact support inside (0,T))
    - HatBasis (piecewise linear, H^1_0)

The first two are smooth enough to support arbitrary derivative orders;
HatBasis handles first-order lifts only.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional

import torch


class TestFunctionBasis:
    """Abstract base class for test-function families on I = (0, T)."""

    T: float
    N: int

    def evaluate(self, ts: torch.Tensor, order: int = 0) -> torch.Tensor:
        """Return phi^{(order)}(ts) as a (len(ts), N) tensor."""
        raise NotImplementedError

    def __len__(self) -> int:
        return self.N

    @property
    def max_derivative_order(self) -> int:
        raise NotImplementedError


class FourierSineBasis(TestFunctionBasis):
    """phi_k(t) = sqrt(2/T) sin(k pi t / T),  k = 1, ..., N.

    Each phi_k lies in H^1_0(I) ∩ C^\\infty and, on (0,T), vanishes at
    the endpoints; derivatives of every order are available analytically.
    The family is L^2-orthonormal.
    """

    def __init__(self, N: int, T: float):
        if N < 1 or T <= 0.0:
            raise ValueError("Need N >= 1 and T > 0.")
        self.N = N
        self.T = T

    @property
    def max_derivative_order(self) -> int:
        return 10**6  # effectively unbounded

    def evaluate(self, ts: torch.Tensor, order: int = 0) -> torch.Tensor:
        if order < 0:
            raise ValueError("order must be >= 0.")
        device, dtype = ts.device, ts.dtype
        k = torch.arange(1, self.N + 1, device=device, dtype=dtype)
        omega = k * (math.pi / self.T)  # (N,)
        arg = ts[:, None] * omega[None, :]  # (T, N)
        amp = math.sqrt(2.0 / self.T)
        shift = (order % 4)
        scale = amp * omega.pow(order)
        if shift == 0:
            base = torch.sin(arg)
        elif shift == 1:
            base = torch.cos(arg)
        elif shift == 2:
            base = -torch.sin(arg)
        else:
            base = -torch.cos(arg)
        return base * scale[None, :]


class BumpBasis(TestFunctionBasis):
    """Compactly supported C^infty bump basis.

    phi_k(t) = rho((t - c_k) / r_k),   rho(s) = exp(-1/(1-s^2)) * 1_{|s|<1}.

    Centers `c_k` are equispaced in the strict interior; supports overlap
    but each phi_k lies in C_c^infty(I). Derivatives are computed by the
    standard recursive formula.
    """

    def __init__(
        self,
        N: int,
        T: float,
        *,
        radius: Optional[float] = None,
        overlap: float = 2.0,
    ):
        if N < 1 or T <= 0.0:
            raise ValueError("Need N >= 1 and T > 0.")
        if radius is None:
            # Place centers so bumps overlap by factor `overlap` times spacing.
            spacing = T / (N + 1)
            radius = min(overlap * spacing, 0.45 * T)
        self.N = N
        self.T = T
        self.radius = float(radius)
        self.centers = torch.linspace(radius, T - radius, N)
        # Max analytic derivative order supported by Python loop below.
        self._max_order = 4

    @property
    def max_derivative_order(self) -> int:
        return self._max_order

    def evaluate(self, ts: torch.Tensor, order: int = 0) -> torch.Tensor:
        if order < 0 or order > self._max_order:
            raise ValueError(
                f"BumpBasis supports order 0..{self._max_order} (got {order})."
            )
        device, dtype = ts.device, ts.dtype
        centers = self.centers.to(device=device, dtype=dtype)
        r = self.radius
        s = (ts[:, None] - centers[None, :]) / r  # (T, N)
        mask = (s.abs() < 1.0 - 1e-12)
        # rho(s) = exp(-1/(1-s^2))
        one_minus = torch.where(mask, 1.0 - s * s, torch.ones_like(s))
        rho = torch.where(mask, torch.exp(-1.0 / one_minus), torch.zeros_like(s))

        if order == 0:
            return rho

        # f'(s) = -2s / (1-s^2)^2 * rho
        inv = 1.0 / one_minus  # 1/(1-s^2)
        d1_ds = -2.0 * s * inv * inv * rho
        if order == 1:
            return torch.where(mask, d1_ds / r, torch.zeros_like(s))

        # f''(s): derivative of (-2s * (1-s^2)^{-2}) * rho + (-2s*(1-s^2)^{-2}) * rho'
        # Let A(s) = -2s*(1-s^2)^{-2}.
        # A'(s) = -2*(1-s^2)^{-2} + (-2s)*(-2)(1-s^2)^{-3}*(-2s)
        #        = -2*(1-s^2)^{-2} - 8 s^2 (1-s^2)^{-3}.
        A = -2.0 * s * inv * inv
        A_prime = -2.0 * inv * inv - 8.0 * s * s * inv * inv * inv
        d2_ds = A_prime * rho + A * d1_ds
        if order == 2:
            return torch.where(mask, d2_ds / (r * r), torch.zeros_like(s))

        # For higher orders: numerical central difference on s-grid.
        # Orders 3,4 are rarely requested; use a small-h finite difference
        # of the analytic d2_ds (still C^infty away from boundary).
        # We fall back to a central difference in s-space directly.
        h = 1e-3
        s_plus = s + h
        s_minus = s - h
        mask_p = (s_plus.abs() < 1.0 - 1e-12)
        mask_m = (s_minus.abs() < 1.0 - 1e-12)
        # compute d2 at s_plus and s_minus
        one_p = torch.where(mask_p, 1.0 - s_plus * s_plus, torch.ones_like(s))
        inv_p = 1.0 / one_p
        rho_p = torch.where(mask_p, torch.exp(-1.0 / one_p), torch.zeros_like(s))
        A_p = -2.0 * s_plus * inv_p * inv_p
        A_prime_p = -2.0 * inv_p * inv_p - 8.0 * s_plus * s_plus * inv_p * inv_p * inv_p
        d1_ds_p = A_p * rho_p
        d2_ds_p = A_prime_p * rho_p + A_p * d1_ds_p

        one_m = torch.where(mask_m, 1.0 - s_minus * s_minus, torch.ones_like(s))
        inv_m = 1.0 / one_m
        rho_m = torch.where(mask_m, torch.exp(-1.0 / one_m), torch.zeros_like(s))
        A_m = -2.0 * s_minus * inv_m * inv_m
        A_prime_m = -2.0 * inv_m * inv_m - 8.0 * s_minus * s_minus * inv_m * inv_m * inv_m
        d1_ds_m = A_m * rho_m
        d2_ds_m = A_prime_m * rho_m + A_m * d1_ds_m

        d3_ds = (d2_ds_p - d2_ds_m) / (2.0 * h)
        if order == 3:
            return torch.where(mask, d3_ds / (r ** 3), torch.zeros_like(s))

        # order == 4 via second central difference
        d4_ds = (d2_ds_p - 2.0 * d2_ds + d2_ds_m) / (h * h)
        return torch.where(mask, d4_ds / (r ** 4), torch.zeros_like(s))


class HatBasis(TestFunctionBasis):
    """Piecewise linear hat functions on a uniform mesh.

    phi_k is the tent centered at t_k = k * h (k=1,...,N), with height 1
    and support [t_{k-1}, t_{k+1}]. In H^1_0(I) but only first-order
    weak derivative (piecewise constant) is well-defined.
    """

    def __init__(self, N: int, T: float):
        if N < 1 or T <= 0.0:
            raise ValueError("Need N >= 1 and T > 0.")
        self.N = N
        self.T = T
        self.h = T / (N + 1)

    @property
    def max_derivative_order(self) -> int:
        return 1

    def evaluate(self, ts: torch.Tensor, order: int = 0) -> torch.Tensor:
        if order not in (0, 1):
            raise ValueError("HatBasis supports only order 0 or 1.")
        device, dtype = ts.device, ts.dtype
        k = torch.arange(1, self.N + 1, device=device, dtype=dtype)
        centers = k * self.h
        # distance from centers, scaled by h
        diff = (ts[:, None] - centers[None, :]) / self.h
        if order == 0:
            val = torch.clamp(1.0 - diff.abs(), min=0.0)
            return val
        # Derivative: +1/h on left slope, -1/h on right slope, 0 elsewhere.
        sign = torch.zeros_like(diff)
        left = (diff > -1.0) & (diff <= 0.0)
        right = (diff > 0.0) & (diff < 1.0)
        sign[left] = 1.0
        sign[right] = -1.0
        return sign / self.h


@dataclass
class Quadrature:
    """Trapezoidal quadrature weights for a uniform or ad-hoc time grid."""

    ts: torch.Tensor  # (N_time,)
    dt: Optional[float] = None  # if None, inferred from ts

    def weights(self) -> torch.Tensor:
        ts = self.ts
        if ts.ndim != 1 or ts.numel() < 2:
            raise ValueError("ts must be 1-D with at least two samples.")
        w = torch.zeros_like(ts)
        dts = ts[1:] - ts[:-1]
        w[:-1] += 0.5 * dts
        w[1:] += 0.5 * dts
        return w


def pair(
    basis: TestFunctionBasis,
    ts: torch.Tensor,
    signal: torch.Tensor,
    *,
    order: int = 0,
) -> torch.Tensor:
    """Compute the pairing <D^order signal, Phi> for smooth (Sobolev) data.

    For `order == 0`:    <signal_i, phi_j> = int_0^T s_i(t) phi_j(t) dt.
    For `order >= 1`:    <D^order signal_i, phi_j> = (-1)^order int s_i phi_j^{(order)} dt
                         (integration by parts; boundary terms vanish for phi in H^1_0(I)).

    This uses a pointwise trapezoidal rule on the provided time grid.

    Args:
        basis: test-function basis of size N_basis.
        ts:    (N_time,) time grid.
        signal: (N_time, d) real-valued signal.
        order: non-negative integer; number of weak derivatives applied to signal.

    Returns:
        (d, N_basis) tensor of pairings.
    """
    if signal.ndim != 2 or signal.shape[0] != ts.shape[0]:
        raise ValueError("signal must have shape (N_time, d) matching ts.")
    if order < 0:
        raise ValueError("order must be >= 0.")
    if order > basis.max_derivative_order:
        raise ValueError(
            f"Basis supports order <= {basis.max_derivative_order}, got {order}."
        )

    phi = basis.evaluate(ts, order=order)  # (N_time, N_basis)
    w = Quadrature(ts).weights().to(signal.dtype).to(signal.device)  # (N_time,)
    sign = (-1.0) ** order
    # <D^order s, phi_j> = sign * sum_k s(t_k) * phi_j^{(order)}(t_k) * w_k.
    weighted = signal * w[:, None]  # (N_time, d)
    return sign * (weighted.T @ phi)


__all__ = [
    "TestFunctionBasis",
    "FourierSineBasis",
    "BumpBasis",
    "HatBasis",
    "Quadrature",
    "pair",
]
